apiVersion: v1
kind: Service
metadata:
  labels:
    name: vsa-api
  name: vsa-api
  namespace: rk-demo
spec:
  ports:
    - protocol: "TCP"
      port: 30004
      targetPort: 80
  selector:
    app: vsa-api
  type: "LoadBalancer"
